--  --
--  insert into App_User (USER_ID, NAME, EMAIL, ENCRYTED_PASSWORD, ENABLED)
--  values (1, 'Ivan Stanev', 'admin@admin.com', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);
--  --
--  insert into App_User (USER_ID, NAME, EMAIL, ENCRYTED_PASSWORD, ENABLED)
--  values (2, 'Pleb Plebski', 'pleb@gmail.com', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);
--  --
--  ---
--  --
--  insert into app_role (ROLE_ID, ROLE_NAME)
--  values (1, 'ROLE_ADMIN');
--  --
--  insert into app_role (ROLE_ID, ROLE_NAME)
--  values (2, 'ROLE_USER');
--  --
--  ---
--  --
--  insert into user_role (ID, USER_ID, ROLE_ID)
--  values (1, 1, 1);
--  --
--  insert into user_role (ID, USER_ID, ROLE_ID)
--  values (2, 1, 2);
--  --
--  insert into user_role (ID, USER_ID, ROLE_ID)
--  values (3, 2, 2);
--  ---
--  --
--  insert into verification_token (TOKEN_ID, TOKEN, USER_ID)
--  values (1,'1111111111',1);

select * from app_user;
